/**
 * Feed Tab Screen ('/(tabs)/feed')
 *
 * Autonomous intelligence feed displaying live insights, routine results,
 * and 1-tap workflow artifacts generated by Cooper and Browserbase.
 */

import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  RefreshControl,
  Platform,
  Linking,
  ActivityIndicator,
} from 'react-native';
import { useRouter } from 'expo-router';
import { HugeiconsIcon } from '@hugeicons/react-native';
import {
  SparklesIcon,
  Globe02Icon,
  Comment01Icon,
  PlayIcon,
  RefreshIcon,
} from '@hugeicons/core-free-icons';
import { Colors } from '@/constants/colors';
import { FeedItem } from '@/types';
import { showToast } from '@/context/ToastContext';
import { ApiService } from '@/services/api';
import { LiveBrowserModal } from '@/components/common';

const CATEGORIES = ['All', 'Autonomous Insight', '1-Tap Idea Execution', 'Goal Execution'];

export default function FeedScreen() {
  const router = useRouter();
  const [feedItems, setFeedItems] = useState<FeedItem[]>([]);
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [refreshing, setRefreshing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [liveModal, setLiveModal] = useState<{ visible: boolean; url: string | null; title?: string }>({
    visible: false,
    url: null,
    title: undefined,
  });

  const loadFeed = useCallback(async () => {
    try {
      const res = await ApiService.getFeed();
      if (res.success && Array.isArray(res.feed)) {
        setFeedItems(res.feed);
      }
    } catch (e: any) {
      console.warn('Failed to load feed:', e.message);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    loadFeed();
  }, [loadFeed]);

  const onRefresh = () => {
    setRefreshing(true);
    loadFeed();
  };

  const handleOpenReplay = (url?: string, title?: string) => {
    if (!url) return;
    setLiveModal({
      visible: true,
      url,
      title: title || 'Browserbase Cloud Replay',
    });
  };

  const handleDiscussInChat = (item: FeedItem) => {
    showToast(`Opening chat on "${item.title}"`);
    router.push('/(tabs)/chat' as any);
  };

  const filteredItems =
    selectedCategory === 'All'
      ? feedItems
      : feedItems.filter((item) => item.category === selectedCategory);

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.headerRow}>
        <View>
          <Text style={styles.pageTitle}>Autonomous Feed</Text>
          <Text style={styles.subtitle}>Real-time updates from Muse AI's cloud operations</Text>
        </View>
        <TouchableOpacity style={styles.refreshBtn} onPress={onRefresh} activeOpacity={0.7}>
          <HugeiconsIcon icon={RefreshIcon} size={18} color={Colors.iconDark} />
        </TouchableOpacity>
      </View>

      {/* Filter Category Chips */}
      <View style={styles.filterWrapper}>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.filterScroll}>
          {CATEGORIES.map((cat) => {
            const isSelected = selectedCategory === cat;
            return (
              <TouchableOpacity
                key={cat}
                style={[styles.filterChip, isSelected && styles.filterChipActive]}
                onPress={() => setSelectedCategory(cat)}
                activeOpacity={0.75}>
                <Text style={[styles.filterChipText, isSelected && styles.filterChipTextActive]}>
                  {cat}
                </Text>
              </TouchableOpacity>
            );
          })}
        </ScrollView>
      </View>

      {/* Feed Cards Stream */}
      {loading ? (
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={Colors.primary} />
          <Text style={styles.loadingText}>Syncing feed stream...</Text>
        </View>
      ) : (
        <ScrollView
          style={styles.scrollArea}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[Colors.primary]} />}>
          {filteredItems.length === 0 ? (
            <View style={styles.emptyContainer}>
              <Text style={styles.emptyEmoji}>📡</Text>
              <Text style={styles.emptyTitle}>No insights in this category yet</Text>
              <Text style={styles.emptyDesc}>
                Execute workflows in the Ideas or Tasks tab to populate your feed stream.
              </Text>
            </View>
          ) : (
            filteredItems.map((item) => (
              <View key={item.id} style={styles.feedCard}>
                {/* Top Badge & Time */}
                <View style={styles.cardTopRow}>
                  <View style={styles.categoryBadge}>
                    <Text style={styles.categoryIcon}>{item.icon}</Text>
                    <Text style={styles.categoryText}>{item.category}</Text>
                  </View>
                  <Text style={styles.timestampText}>{item.timestamp}</Text>
                </View>

                {/* Headline */}
                <Text style={styles.headlineTitle}>{item.title}</Text>

                {/* Summary */}
                <Text style={styles.summaryText}>{item.summary}</Text>

                {/* Tags */}
                {item.tags && item.tags.length > 0 && (
                  <View style={styles.tagsRow}>
                    {item.tags.map((tag, idx) => (
                      <View key={`tag-${idx}`} style={styles.tagPill}>
                        <Text style={styles.tagText}>#{tag}</Text>
                      </View>
                    ))}
                  </View>
                )}

                {/* Footer Actions */}
                <View style={styles.cardFooter}>
                  {item.replayUrl && (
                    <TouchableOpacity
                      style={styles.replayBtn}
                      onPress={() => handleOpenReplay(item.replayUrl, item.title)}
                      activeOpacity={0.75}>
                      <HugeiconsIcon icon={Globe02Icon} size={13} color={Colors.primary} strokeWidth={2} />
                      <Text style={styles.replayBtnText}>Watch Cloud Replay</Text>
                    </TouchableOpacity>
                  )}

                  <TouchableOpacity
                    style={styles.chatActionBtn}
                    onPress={() => handleDiscussInChat(item)}
                    activeOpacity={0.75}>
                    <HugeiconsIcon icon={Comment01Icon} size={14} color={Colors.textSecondary} strokeWidth={2} />
                    <Text style={styles.chatActionText}>Discuss</Text>
                  </TouchableOpacity>
                </View>
              </View>
            ))
          )}
        </ScrollView>
      )}

      {/* Embedded Live Cloud Browser Modal */}
      <LiveBrowserModal
        visible={liveModal.visible}
        url={liveModal.url}
        title={liveModal.title}
        onClose={() => setLiveModal({ visible: false, url: null })}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: Colors.iconDark,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  refreshBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterWrapper: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F2',
  },
  filterScroll: {
    paddingHorizontal: 20,
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
  },
  filterChipActive: {
    backgroundColor: Colors.iconDark,
  },
  filterChipText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  filterChipTextActive: {
    color: Colors.white,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  loadingText: {
    fontSize: 14,
    color: Colors.textSecondary,
  },
  scrollArea: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 28,
    gap: 14,
  },
  feedCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EAECEF',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  categoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primarySubtle,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    gap: 5,
  },
  categoryIcon: {
    fontSize: 13,
  },
  categoryText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: Colors.primary,
  },
  timestampText: {
    fontSize: 12,
    color: Colors.textMuted,
    fontWeight: '500',
  },
  headlineTitle: {
    fontSize: 16.5,
    fontWeight: '700',
    color: Colors.iconDark,
    lineHeight: 22,
    letterSpacing: -0.2,
    marginBottom: 6,
  },
  summaryText: {
    fontSize: 13.5,
    color: '#4B5563',
    lineHeight: 20,
    marginBottom: 12,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 14,
  },
  tagPill: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  tagText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  replayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: Colors.primarySubtle,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  replayBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.primary,
  },
  chatActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  chatActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 30,
    gap: 10,
  },
  emptyEmoji: {
    fontSize: 40,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.iconDark,
    textAlign: 'center',
  },
  emptyDesc: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
  },
});
